Repository GeeksCAT/hacktoberfest-web-2023, pull requests merged in 2023-09, with the labels that each got.

#1 Feat/diary
  src/components/Sections/SDiary.vue
  src/components/Sections/SMenu.vue
  src/views/Home.vue
Labels: HACKTOBERFEST-ACCEPTED

#4 Prioritize event schedule
  src/views/Home.vue
Labels: enhancement, HACKTOBERFEST-ACCEPTED

#7 Feature/reactivate join call2action
  src/components/Atoms/AButton.vue
  src/components/Sections/SCall4Sponsors.vue
  src/components/Sections/SDiary.vue
  src/components/Sections/SJoin.vue
  src/components/Sections/SWhatWeWillDoLite.vue
  src/content.ts
  src/views/Home.vue
Labels: enhancement, HACKTOBERFEST-ACCEPTED

#8 Feature/add ajgirona title
  src/components/Modules/MLogosGallery.vue
  src/content.ts
  src/types.ts
Labels: enhancement, HACKTOBERFEST-ACCEPTED

#9 fix: fix some diary row spans
  src/components/Sections/SDiary.vue
Labels: bug, HACKTOBERFEST-ACCEPTED
